//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nha_Hang_Huit.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NhaHangHUITEntities : DbContext
    {
        public NhaHangHUITEntities()
            : base("name=NhaHangHUITEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCa> tblCa { get; set; }
        public virtual DbSet<tblChiTietHoaDon> tblChiTietHoaDon { get; set; }
        public virtual DbSet<tblHangThe> tblHangThe { get; set; }
        public virtual DbSet<tblHoaDon> tblHoaDon { get; set; }
        public virtual DbSet<tblKhachHang> tblKhachHang { get; set; }
        public virtual DbSet<tblLichSuDiemKhachHang> tblLichSuDiemKhachHang { get; set; }
        public virtual DbSet<tblMonAn> tblMonAn { get; set; }
        public virtual DbSet<tblNhanVien> tblNhanVien { get; set; }
        public virtual DbSet<tblNhomMonAn> tblNhomMonAn { get; set; }
    }
}
