//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nha_Hang_Huit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCa()
        {
            this.tblHoaDon = new HashSet<tblHoaDon>();
        }
    
        public int MaCa { get; set; }
        public int MaNhanVien { get; set; }
        public System.DateTime ThoiGianMoCa { get; set; }
        public Nullable<System.DateTime> ThoiGianDongCa { get; set; }
        public int TongHoaDon { get; set; }
        public decimal TongDoanhThu { get; set; }
        public decimal TongGiamGia { get; set; }
        public decimal DoanhThuThucNhan { get; set; }
        public string GhiChu { get; set; }
        public string TrangThai { get; set; }
    
        public virtual tblNhanVien tblNhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHoaDon> tblHoaDon { get; set; }
    }
}
