//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nha_Hang_Huit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChiTietHoaDon
    {
        public int MaChiTiet { get; set; }
        public int MaHoaDon { get; set; }
        public int MaMonAn { get; set; }
        public string TenMonAn { get; set; }
        public decimal DonGia { get; set; }
        public int SoLuong { get; set; }
        public Nullable<decimal> ThanhTien { get; set; }
        public string GhiChu { get; set; }
    
        public virtual tblHoaDon tblHoaDon { get; set; }
        public virtual tblMonAn tblMonAn { get; set; }
    }
}
