//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nha_Hang_Huit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHangThe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblHangThe()
        {
            this.tblKhachHang = new HashSet<tblKhachHang>();
        }
    
        public int MaHang { get; set; }
        public string TenHang { get; set; }
        public int DiemToiThieu { get; set; }
        public int DiemToiDa { get; set; }
        public decimal TyLeGiamGia { get; set; }
        public string MoTa { get; set; }
        public string MauHienThi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblKhachHang> tblKhachHang { get; set; }
    }
}
