//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nha_Hang_Huit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblHoaDon()
        {
            this.tblChiTietHoaDon = new HashSet<tblChiTietHoaDon>();
            this.tblLichSuDiemKhachHang = new HashSet<tblLichSuDiemKhachHang>();
        }
    
        public int MaHoaDon { get; set; }
        public int MaCa { get; set; }
        public Nullable<int> MaKhachHang { get; set; }
        public int SoBan { get; set; }
        public System.DateTime ThoiGianTao { get; set; }
        public Nullable<System.DateTime> ThoiGianThanhToan { get; set; }
        public decimal TongTienGoc { get; set; }
        public decimal SoTienGiamGia { get; set; }
        public decimal TongThanhToan { get; set; }
        public decimal SoTienKhachDua { get; set; }
        public decimal TienThua { get; set; }
        public string HinhThucTT { get; set; }
        public int DiemTichLuy { get; set; }
        public string TrangThai { get; set; }
    
        public virtual tblCa tblCa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChiTietHoaDon> tblChiTietHoaDon { get; set; }
        public virtual tblKhachHang tblKhachHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLichSuDiemKhachHang> tblLichSuDiemKhachHang { get; set; }
    }
}
