//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nha_Hang_Huit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLichSuDiemKhachHang
    {
        public int MaLichSu { get; set; }
        public int MaKhachHang { get; set; }
        public Nullable<int> MaHoaDon { get; set; }
        public string LoaiGiaoDich { get; set; }
        public int SoDiem { get; set; }
        public int DiemSauGiaoDich { get; set; }
        public System.DateTime ThoiGian { get; set; }
        public string GhiChu { get; set; }
    
        public virtual tblHoaDon tblHoaDon { get; set; }
        public virtual tblKhachHang tblKhachHang { get; set; }
    }
}
