//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nha_Hang_Huit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMonAn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblMonAn()
        {
            this.tblChiTietHoaDon = new HashSet<tblChiTietHoaDon>();
        }
    
        public int MaMonAn { get; set; }
        public int MaNhom { get; set; }
        public string TenMonAn { get; set; }
        public decimal GiaBan { get; set; }
        public string DonVi { get; set; }
        public string MoTa { get; set; }
        public string DuongDanHinh { get; set; }
        public bool TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChiTietHoaDon> tblChiTietHoaDon { get; set; }
        public virtual tblNhomMonAn tblNhomMonAn { get; set; }
    }
}
