//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nha_Hang_Huit.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNhomMonAn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblNhomMonAn()
        {
            this.tblMonAn = new HashSet<tblMonAn>();
        }
    
        public int MaNhom { get; set; }
        public string TenNhom { get; set; }
        public string MoTaNhom { get; set; }
        public int ThuTuHienThi { get; set; }
        public bool TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMonAn> tblMonAn { get; set; }
    }
}
